### PR TITLE
Update calico to  v3.13.1

### PR DESCRIPTION
**Pull request by majst01**
**What this PR does / why we need it**:

We found some differences between the charts shipped here and upstream calico. I changed:

calico update from 3.11.2 -> 3.13.1
calico-node liveness probe
calico-node got one more rbac rule
enlarge calico-node cpu requests

This should fix a bug with felix liveliness probe not finishing in 1sec and causes crashing calico-node pods on workers with more than 100pods. 

Felix fix: https://github.com/projectcalico/felix/pull/2215

**Release note**:
```noteworthy operator
Calico is updated to v3.13.1
```

### CODE REVIEW

**Comment by majst01** [comment]
@zanetworker will this pr create a image ? if yes what would be the tag ?

**Comment by zanetworker** [comment]
@majst01 yes, it had already created an image, the tag you can use is: `eu.gcr.io/gardener-project/gardener/extensions/networking-calico:v1.4.0-dev-74858ec4d201e799493005384139fb8ef63531c2` I am also planning to test it.

**Comment by majst01** [comment]
Deployment to our testing environment currently in progress, will report back.

**Comment by majst01** [comment]
All seems fine, but we have one error log entry in the genc which we hadnt before:
```
gardener-extension-networking-calico-76595f66b5-ck5rh gardener-extension-networking-calico {"level":"error","ts":"2020-03-19T12:00:41.549Z","logger":"shoot-not-failed","msg":"Could not retrieve corresponding cluster","error":"Cluster.extensions.gardener.cloud \"shoot--p4klj7--cn-devops\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/gardener/gardener-extensions/pkg/predicate.(*shootNotFailedMapper).Map\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/github.com/gardener/gardener-extensions/pkg/predicate/predicate.go:74\ngithub.com/gardener/gardener-extensions/pkg/predicate.(*mapperWithTriggers).Create\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/github.com/gardener/gardener-extensions/pkg/predicate/mapper.go:77\nsigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnAdd\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/sigs.k8s.io/controller-runtime/pkg/source/internal/eventsource.go:68\nk8s.io/client-go/tools/cache.(*processorListener).run.func1.1\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292\nk8s.io/client-go/tools/cache.(*processorListener).run.func1\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nk8s.io/client-go/tools/cache.(*processorListener).run\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\t/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71"}
gardener-extension-networking-calico-76595f66b5-ck5rh gardener-extension-networking-calico {"level":"info","ts":"2020-03-19T12:01:15.390Z","logger":"network_controller","msg":"Starting the reconciliation of network","network":"stefan"}
gardener-extension-networking-calico-76595f66b5-ck5rh gardener-extension-networking-calico {"level":"info","ts":"2020-03-19T12:01:15.421Z","logger":"network_controller","msg":"Successfully reconciled network","network":"stefan"}
```
any clue here ?

**Comment by zanetworker** [comment]
@majst01  whats the output of `kubectl api-resources | grep cluster` for you?

**Comment by majst01** [comment]
```
kubectl --kubeconfig seed  api-resources | grep cluster
clusterinformations                                crd.projectcalico.org          false        ClusterInformation
clusters                                           extensions.gardener.cloud      false        Cluster
clusterrolebindings                                rbac.authorization.k8s.io      false        ClusterRoleBinding
clusterroles                                       rbac.authorization.k8s.io      false        ClusterRole
```

**Comment by zanetworker** [comment]
is your gardenlet healthy and running? the cluster resource should be created during reconciliation.

**Comment by zanetworker** [comment]
I see that your testing with a mock `Network` resource named `stefan` also does the namespace  `shoot--p4klj7--cn-devops` correspond to a real / functional control-plane?

**Comment by majst01** [comment]
gardenlet is healthy and running, what resource is missing ?
What do you mean by `mock` Network ?

**Comment by zanetworker** [comment]
I mean that it was not manually created by you for the sake of testing not during the reconciliation, otherwise it would have been named `cn-devops`.

**Comment by majst01** [comment]
no not manually created all shoot namespaces are named that way in our seed, not configured by us, gardener default.

**Comment by zanetworker** [comment]
@majst01 I meant the network resource :)

**Comment by Gerrit91** [comment]
BTW: The error had nothing to do with the extension controller itself. It is a state in our test seed, which is a bit broken and I think it was caused by forced namespace deletion in the seed.

**Comment by zanetworker** [comment]
@Gerrit91  thanks for the comment. already discussed it with Stefan on another channel :)

**Pull request merged**
