### PR TITLE
Vendor `gardener@1.79.1` and Upgrade go, k8s dependencies and controller-runtime

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
Vendor `gardener@1.79.1`.
Update go version in go.mod to 1.21.
Also embed remaining charts and drop copying charts to the container.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
The following dependency is updated:
- github.com/gardener/gardener: v1.77.2 -> v1.79.1
- k8s.io/* : v0.26.3 -> v0.27.5
- sigs.k8s.io/controller-runtime: v0.14.6-> v0.15.2
```

### CODE REVIEW

**Review by ScheererJ — APPROVED** [review]
Thanks for the change.

/lgtm

**Comment by shafeeqes** [comment]
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener-extension-networking-calico/296/pull-extension-networking-calico/1704444593921069056#1:build-log.txt%3A5

```
Error during calling make revendor: make[1]: Entering directory '/home/prow/go/src/github.com/gardener/gardener-extension-networking-calico'
push_pin
go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20
```

🤔

**Comment by ScheererJ** [comment]
> https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener-extension-networking-calico/296/pull-extension-networking-calico/1704444593921069056#1:build-log.txt%3A5
> 
> ```
> Error during calling make revendor: make[1]: Entering directory '/home/prow/go/src/github.com/gardener/gardener-extension-networking-calico'
> push_pin
> go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20
> ```
> 
> 🤔

I think that you need to update branch `refs/meta/ci` as the golang version is referenced there in the template.

**Comment by shafeeqes** [comment]
> I think that you need to update branch `refs/meta/ci` as the golang version is referenced there in the template.

Do you mean https://github.com/gardener/gardener-extension-networking-calico/commit/5ac019fbc6f44b0d1ef18c1234c668436bc1cbd0?

**Comment by ScheererJ** [comment]
> > I think that you need to update branch `refs/meta/ci` as the golang version is referenced there in the template.
> 
> Do you mean [5ac019f](https://github.com/gardener/gardener-extension-networking-calico/commit/5ac019fbc6f44b0d1ef18c1234c668436bc1cbd0)?

Yes, that was my thinking, but that does not seem to be the problem.

**Comment by shafeeqes** [comment]
https://github.com/gardener/ci-infra/pull/904 should fix it

**Comment by shafeeqes** [comment]
The tests passed. Merging it.

**Pull request merged**
