### PR TITLE
Fixed calico autoscaling, typha rollout strategy, calico log level, increased typha cpu limits, increased calico autoscaler memory limits, and increased revision history limit.

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/kind cleanup

**What this PR does / why we need it**:
Fixed calico autoscaling, typha rollout strategy, calico log level, increased typha cpu limits, increased calico autoscaler memory limits, and increased revision history limit.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```other operator
Fixed calico autoscaling, typha rollout strategy, calico log level, increased typha cpu limits, increased calico autoscaler memory limits, and increased revision history limit.
```

### CODE REVIEW

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Review by dguendisch — APPROVED** [review]
/lgtm

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Pull request merged**
