### PR TITLE
Vendor `gardener@v1.52.0`

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Vendor `gardener@v1.52.0`
https://github.com/gardener/gardener/releases/tag/v1.52.0
https://github.com/gardener/gardener/releases/tag/v1.51.0

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
The following dependency is updated:
- github.com/gardener/gardener: v1.50.1 -> v1.52.0
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
Please adapt HVPA similar to https://github.com/gardener/gardener-extension-provider-azure/pull/541

**Review by ScheererJ — DISMISSED** [review]
/lgtm

**Comment by shafeeqes** [comment]
Force pushed the branch to retrigger the pending tests.

**Comment by ScheererJ** [comment]
@shafeeqes Why is the commit "update calico to v3.23.3" included in this pull request? It was already merged. I am confused now.

**Comment by shafeeqes** [comment]
> @shafeeqes Why is the commit "update calico to v3.23.3" included in this pull request? It was already merged. I am confused now.

Sorry, forgot to rebase. Pushed again. PTAL.

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Pull request merged**
