### PR TITLE
Updated to gardener 1.25.0

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Updated dependencies to gardener 1.25.0

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by ScheererJ** [comment]
Properly revendored again.

**Comment by ScheererJ** [comment]
Updated vendor/modules.txt.

**Comment by vpnachev** [comment]
You need to run 
```bash
$ make install-requirements
$ make generate
```

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Pull request merged**
