### PR TITLE
Bump cluster-proportional-vertical-autoscaler

### PR DESCRIPTION
**Pull request by tim-ebert**
**How to categorize this PR?**

/area robustness
/kind bug
/priority normal
/area networking

**What this PR does / why we need it**:
Bump the version of `cluster-proportional-vertical-autoscaler` to the [newest release](https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler/releases/tag/v0.8.3), which contains a [fix](https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler/pull/36) for errors like this one:
```
$ ks logs -f calico-node-vertical-autoscaler-798d9d954f-gvczw
I0529 06:28:44.643989       1 autoscaler.go:46] Scaling namespace: kube-system, target: daemonset/calico-node
E0529 06:28:47.143862       1 autoscaler.go:49] failed to discover apigroup for kind "DaemonSet": unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
cc @rfranzke 

**Release note**:

```improvement user
Fixed a bug, which caused `calico-typha-vertical-autoscaler` and `calico-node-vertical-autoscaler` to crash, when there are undiscoverable `APIService`s.
```

### CODE REVIEW

**Comment by tim-ebert** [comment]
Do we want to make a patch release `v1.7.2` with this fix?

**Comment by ialidzhikov** [comment]
> Do we want to make a patch release v1.7.2 with this fix?

Generally it would be good to have a release with this version bump but it is not critical as we were hitting this issue since longtime.

**Comment by zanetworker** [comment]
@tim-ebert I cherry picked your version bump to the 1.7 release branch but the patch release was not triggerred, @ialidzhikov any idea why?

**Comment by tim-ebert** [comment]
I think, you have to trigger it manually, right?
https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-extension-networking-calico-release-v1.7/jobs/release-v1.7-release-job/builds/1

**Comment by zanetworker** [comment]
yes, its already released, thanks for bumping :)

**Pull request merged**
