### PR TITLE
Vendor `gardener/gardener` `v1.65.0`

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Vendor gardener/gardener `v1.65.0`

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
I have removed the health check controller, since there was only one health check for ManagedResource and condition `ShootSystemComponentsHealthy`, these are already health checked by gardener now. If you need to add some specific error code checks or add health check for some other condition, this controller shall be added again.

**Release note**:

```other dependency
The following dependency is updated:
- github.com/gardener/gardener: v1.64.0 -> v1.65.0
```

### CODE REVIEW

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Review by ScheererJ — COMMENTED** [review]
Looks good in general.

Could you please check why `verify` is failing?

**Review by ScheererJ — COMMENTED** [review]
Could you please share your reasoning why you removed the test directory from several makefile targets?

**Comment by shafeeqes** [comment]
> Could you please share your reasoning why you removed the test directory from several makefile targets?

Because the test directory itself is removed with https://github.com/gardener/gardener-extension-networking-calico/pull/245/commits/27393b98e4748f5b8cc7b911e6b6e8416f89423d

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Pull request merged**
