### PR TITLE
Add security context to install-cni container

### PR DESCRIPTION
**Pull request by DockToFuture**
**How to categorize this PR?**

/area networking
/kind enhancement
/priority normal

**What this PR does / why we need it**:

Add security context to install-cni container

**Special notes for your reviewer**:

**Release note**:

```other operator
Add security context to install-cni container
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Can you explain more why you propose this change? The change itself looks good, but it would be interesting to know the backgrounds.
/invite @mvladev

**Comment by rfranzke** [comment]
@DockToFuture ?

**Comment by DockToFuture** [comment]
Sometimes we are seeing that calico cni plugin is missing on the nodes and so far the logs say that it were successfully installed but it is missing. It was either not installed or somehow deleted afterwards. Since I wasn't able in reproducing this problem locally and the only difference to the provided charts from calico is, that we are lacking the security context in the init container. I would like to add the security context to see that it is not related and since we are using it anyhow in the calico node, I see no objections against it. If you however can exclude that, we can close the PR. :)

**Review by rfranzke — APPROVED** [review]
> and the only difference to the provided charts from calico is, that we are lacking the security context in the init container which install the binary.

Ah, I see, yeah, of course, we should follow what the Project Calico maintainers are providing as examples. Thanks for the explanation!

/lgtm

**Pull request merged**
