### PR TITLE
Switch the calico images to be pulled from quay.io

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
See https://github.com/gardener/gardener-extension-networking-calico/issues/274

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener-extension-networking-calico/issues/274

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
networking-calico does no longer use Gardener GCR copies for the calico images. Instead, the upstream quay.io container images are used (`quay.io/calico/node`, `quay.io/calico/cni`, `quay.io/calico/typha`, `quay.io/calico/kube-controllers`).
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
@timebertt @robinschneider are you ok with this change? Does quay.io support image pulls over IPv6?

**Comment by robinschneider** [comment]
I looked it up and as far as I could find out, quay.io seems to be IPv4 only.

**Comment by ialidzhikov** [comment]
Is it? How you check this?

```
% host quay.io
quay.io has address 34.237.27.205
quay.io has address 34.237.31.230
quay.io has address 52.44.162.2
quay.io has address 52.206.40.42
quay.io has address 3.87.166.194
quay.io has address 3.210.148.47
quay.io has address 3.224.204.235
quay.io has address 23.20.135.143
quay.io has IPv6 address 2600:1f18:483:cf01:33f6:d7d4:a9b1:e3ce
quay.io has IPv6 address 2600:1f18:483:cf01:6456:d087:d0c8:2d01
quay.io has IPv6 address 2600:1f18:483:cf01:d5f4:94ce:f190:aeaf
quay.io has IPv6 address 2600:1f18:483:cf02:68bb:2416:361c:5b8a
quay.io has IPv6 address 2600:1f18:483:cf02:e10b:8bbe:7d4c:1871
quay.io has IPv6 address 2600:1f18:483:cf00:1735:7dca:f93a:907f
quay.io has IPv6 address 2600:1f18:483:cf00:3003:c77b:dfa8:94fc
quay.io has IPv6 address 2600:1f18:483:cf00:521a:3ba6:1b12:e130
quay.io mail is handled by 1 us-smtp-inbound-1.mimecast.com.
```

**Comment by robinschneider** [comment]
Sorry, you are right. I googled it and it seems they added support in December last year. My previous answer was from an older information I found online.

image

**Comment by ialidzhikov** [comment]
gardener/gardener deploys several quay.io images to the Seed controlplane and to the Shoot itself:
```
quay.io/prometheus/blackbox-exporter:v0.23.0
quay.io/prometheus/node-exporter:v1.5.0
quay.io/prometheus/alertmanager:v0.24.0
quay.io/prometheus/prometheus:v2.43.1
quay.io/brancz/kube-rbac-proxy:v0.14.2
```

If it was not observed that image pull fails for these images on ipv6 cluster, then I assume we can proceed with this PR.

**Comment by ScheererJ** [comment]
I was wondering who pushes the container images to quay.io, but I at least found that calico seem to have quay.io in their mind (see https://github.com/projectcalico/calico/blob/master/hack/release/RELEASING.md).

@ialidzhikov Do you have more information regarding this? While I agree that we should remove unnecessary copying, I do not want to rely on random persons uploading to quay.io, which could obviously be a security risk as well. Therefore, I prefer to use the primary source unless there is some statement from project calico that they will also update quay.io with every release.

**Comment by ialidzhikov** [comment]
In the past we were using quay.io images for a long time. ~2years ago the images were switched from quay.io ones to dockerhub ones - ref https://github.com/gardener/gardener-extension-networking-calico/pull/64/files. I don't know/recall the exact reason for it. When I look into https://quay.io/repository/calico/node?tab=tags, I think that it is rather the calico machinery (CI/CD) that updates these images. It is not like a maintained mirror on a best effort from an individual. You can see that HEAD/master images are pushed regularly. I don't think someone does this manually.

Ref https://github.com/projectcalico/calico/blob/01c9ed481d780ee151d2db5f2e4a9916ef2e7bf2/metadata.mk#L33-L36
quay.io seems a good choice for me for now. As shared in https://github.com/gardener/gardener-extension-networking-calico/pull/275#issuecomment-1582073876, in gardener/gardener we already have several other images from quay.io.
If you want GCR images, I can use the ones from https://console.cloud.google.com/gcr/images/projectcalico-org/EU. It seems that calico is even pushing to GCR.

**Comment by ScheererJ** [comment]
I am not opposed to using quay.io instead of docker.io. Let me check with @DockToFuture once he is back from his vacation whether there was more to https://github.com/gardener/gardener-extension-networking-calico/pull/64#discussion_r560871245. I do not see any mention of a change with regards to this in the calico release notes.

@ialidzhikov Can this wait another 10 days or is it time-critical?

**Comment by ialidzhikov** [comment]
> I uploaded them manually, they switched from `quay.io` to `docker`.

I don't know what the above statement means and in which context it is said. Maybe @DockToFuture means that calico charts in the upstream switched to dockerhub by default back then?

> @ialidzhikov Can this wait another 10 days or is it time-critical?

Sure, no problem. I don't think @DockToFuture will recall any concrete reasons but anyways.
I see that calico images are well maintained in quay.io and in GCRs (ref https://github.com/projectcalico/calico/blob/01c9ed481d780ee151d2db5f2e4a9916ef2e7bf2/hack/release/pkg/builder/builder.go#L29-L37). IMO, using any of them should be fine.

**Review by vpnachev — APPROVED** [review]
/lgtm

**Comment by vpnachev** [comment]
Taking a look https://github.com/projectcalico/calico/issues/4833#issuecomment-1209612283, I don't think we have to wait for @DockToFuture to come back from vacation. 

The reason why calico community switched the default registry from quay to docker in the past was that quay was not supporting multi arch images back then, ref https://github.com/projectcalico/calico/issues/4227#issuecomment-735997033.

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Comment by DockToFuture** [comment]
Both registries are supported. We can switch to quay.io.

**Comment by ialidzhikov** [comment]
I decided to cherry-pick this PR as currently prow is using networking-calico and the copied images in GCR are used for the tests in prow. This increases the network costs as prow tests currently pull the calico images from our GCR.
Ref https://github.com/gardener/gardener-extension-networking-calico/pull/277

**Pull request merged**
