### PR TITLE
do not disable kubeController with backend none

### PR DESCRIPTION
**Pull request by mwennrich**
/area networking
/kind TODO
/priority normal

**What this PR does / why we need it**:

Currently setting `backend` to `none` in the shoot.spec disables the calico-kube-controllers: https://github.com/gardener/gardener-extension-networking-calico/blob/master/pkg/charts/utils.go#L178-L182

This even overrules the explicit setting of `kubeControllers.enabled: true`

This PR removes this behavior and therefore allows shoots with `backend: none` to have calico-kube-controllers installed.

Users of gardener-extension-networking-calico with `backend: none` who do not want kubeControllers enabled, should disable kubeControllers (`kubeControllers.enabled: false`) in the shoot spec.

**Special notes for your reviewer**:

Attention: this changes the default behavior for clusters with `backend: none`. Cluster-admins who wish to have kubeControllers disabled should make sure, that kubeControllers.enabled is set to false before upgrading. (Clusters with any other backend (bird, vxlan) are unaffected.)

**Release note**:
Allow enabling of calico-kube-controllers for clusters with `backend: none`
**Attention**: this changes the default behavior for clusters with `backend: none`. Cluster-admins who wish to have kubeControllers disabled should make sure, that kubeControllers.enabled is set to false before upgrading. (Clusters with any other backend (bird, vxlan) are unaffected.)

```other operator

```

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @mwennrich for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by danielfoehrKn** [comment]
@DockToFuture could you please check this PR when you got the time?  Thanks.

**Comment by ScheererJ** [comment]
Hi @mwennrich,

could you please comment why you think that the kube-controllers are required in the calico scenario with backend set to none? In our use case, i.e. using the kubernetes datastore as backend for calico, only the node controller is relevant at all (see https://docs.projectcalico.org/reference/kube-controllers/configuration for details). However, we do not use any of the node specific calico resources which would need to be cleaned up, e.g. ipam blocks, when we do not use a backend.

Please share your scenario details.

Best regards

**Comment by mwennrich** [comment]
Yes, sorry, you're right ... my initial thought was, that we need the policy controller for "policy-only" mode ... but most of these controllers are only needed when using etcd as datastore. Closing.

**Comment by ScheererJ** [comment]
Indeed, the name calico-kube-controllers suggests a lot more than it actually does when used with kubernetes as datastore.
Thanks anyway for your pull request.

**Pull request closed without merging**
