### PR TITLE
Adapt PDBs to use `unhealthyPodEvictionPolicy: AlwaysAllow`

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
- Add `unhealthyPodEvictionPolicy: AlwaysAllow` to PDBs

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/8821

**Special notes for your reviewer**:

**Release note**:

```breaking operator
NONE
```

### CODE REVIEW

**Review by DockToFuture — DISMISSED** [review]
lgtm

**Comment by DockToFuture** [comment]
@shafeeqes did you test the PR as the e2e tests are failing?

**Comment by shafeeqes** [comment]
> @shafeeqes did you test the PR as the e2e tests are failing?
> 
> ```
> 2024-02-14T14:38:22.684444904Z stderr F {"level":"error","ts":"2024-02-14T14:38:22.684Z","msg":"Reconciler error","controller":"controllerinstallation","namespace":"","name":"networking-calico-btdqr","reconcileID":"c5db697b-a291-4164-b13d-42cfa64cd040","error":"render error in \"gardener-extension-networking-calico/templates/poddisruptionbudget.yaml\": template: gardener-extension-networking-calico/templates/poddisruptionbudget.yaml:13:46: executing \"gardener-extension-networking-calico/templates/poddisruptionbudget.yaml\" at <.Capabilities.KubeVersion.Version>: can't evaluate field Version in type *version.Info","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227"}
> ```

Should be fixed now.

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Pull request merged**
