### PR TITLE
Update cluster-proportional-autoscaler image

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area networking
/kind enhancement

**Release note**:

```other operator
The following image is updated:
- k8s.gcr.io/cpa/cluster-proportional-autoscaler: v1.8.5 -> v1.8.6
```

### CODE REVIEW

**Comment by ScheererJ** [comment]
I am confused.
According to https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases 1.8.5 was released yesterday, but we seem to use it since over a month already (https://github.com/gardener/gardener-extension-networking-calico/pull/190/files). The [cluster proportional autoscaler repository](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler) does not mention 1.8.6, but at least in the [kubernetes staging repository tree](https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-cpa/images.yaml) there is 1.8.6 (only without architecture suffix).

@ialidzhikov Could you please clarify what is going on in case you understand it?

**Comment by ialidzhikov** [comment]
The tag exists - ref https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/tree/1.8.6. But there is no release yet. The image promotion PR was merged 1/2 days ago - ref https://github.com/kubernetes/k8s.io/pull/4026. I expect the 1.8.6 to be released soon. I don't have idea why https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.5 appears to be released yesterday. I think only @MrHohn is able to answer the questions from https://github.com/gardener/gardener-extension-networking-calico/pull/206#issuecomment-1214752161. @MrHohn, could you please do so? Thanks in advance!
If you have concerns we can also hold the PR until the github release is cut.

About the motivation for this PR: You know that we internally mirror OSS container images to our own registry. `cluster-proportional-autoscaler@1.8.5` container image (and its old versions) were not mirrored in multi-arch way. The issue should be fixed internally on our CI/CD side. But the existing mirror of `cluster-proportional-autoscaler@1.8.5` is not yet multi-arch. This PR updates to `cluster-proportional-autoscaler@1.8.6` to kick our CI/CD to finally properly mirror the `cluster-proportional-autoscaler` container image finally in a proper way so it is a multi-arch image as expected.

**Comment by acumino** [comment]
> I am confused. According to https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases 1.8.5 

@ScheererJ 1.8.5 release date is not yesterday but a year back.
>The [cluster proportional autoscaler repository](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler) does not mention 1.8.6, but at least in the [kubernetes staging repository tree](https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-cpa/images.yaml) there is 1.8.6

The image has been published but the release is still not there that I am not sure why.

**Comment by acumino** [comment]
> About the motivation for this PR: You know that we internally mirror OSS container images to our own registry. cluster-proportional-autoscaler@1.8.5 container image (and its old versions) were not mirrored in multi-arch way. The issue should be fixed internally on our CI/CD side. But the existing mirror of cluster-proportional-autoscaler@1.8.5 is not yet multi-arch. This PR updates to cluster-proportional-autoscaler@1.8.6 to kick our CI/CD to finally properly mirror the cluster-proportional-autoscaler container image so that it is a multi-arch image as expected.

Yes.

>Maybe the mirroring was not working so far due to https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/issues/123.

But the reason our CI/CD doesn't replicate images properly(multi-arch) is that in past there was no need. The issue is not related to multi-arch image but is related to only arm specific image.

**Review by acumino — APPROVED** [review]
/lgtm
/hold Probably we should wait till a release is also there. Please unhold we don't want to wait for the release.

**Comment by MrHohn** [comment]
https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.6 is out now :)

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Pull request merged**
